version: 2.1
workflows:
  Build multi-arch images:
    jobs:
      - x86-image

jobs:
  x86-image:
    machine: true
    resource_class: mayurwaghmode/alkalify1-x86-runner
    working_directory: /root
    steps: 
    - run: |
         sudo rm -rf /root/$GH_REPO
         echo $QUAY_REPO:$(uname -m)
         git clone -b hosted-multi-arch https://github.com/mayurwaghmode/circleCI-multi-arch.git /root/$GH_REPO
         cd /root/$GH_REPO
         buildah bud -f Dockerfile -t $QUAY_REPO:$(uname -m) .
         buildah login -u $QUAY_USER -p $QUAY_PWD $QUAY_REPO:$(uname -m)
         podman push $QUAY_REPO:$(uname -m)
