version: 2.1
workflows:
  Build multi-arch images:
    jobs:
      - x86-image

jobs:
  x86-image:
    machine: true
    resource_class: mayurwaghmode/alkalify1-x86-runner
    steps:
      - run: |
         buildah bud -f Dockerfile -t $QUAY_REPO:$(uname -m) .
         buildah login -u $QUAY_USER -p $QUAY_PWD quay.io
         podman push $QUAY_REPO:$(uname -m)
